Try clash resolution
AY2223S2-CS2113-T13-4/tp pull request #117
Opened 2023-03-19 13:55 UTC by PoobalanAatmikaLakshmi

2023-03-21 08:54 UTC, yixuann02 commented on src/main/java/seedu/apollo/storage/Storage.java
> +import seedu.apollo.exception.task.*;
Perhaps you could list out all the classes instead of using *

2023-03-21 08:54 UTC, yixuann02 commented on src/main/java/seedu/apollo/task/Event.java
> +
Perhaps you could add some JavaDoc for these methods

2023-03-21 08:54 UTC, yixuann02 commented on src/main/java/seedu/apollo/ui/Ui.java
>  }
Do add JavaDocs for these as well

2023-03-21 08:54 UTC, yixuann02 commented on src/main/java/seedu/apollo/command/module/AddModuleCommand.java
> +            if (module1.getCode().equalsIgnoreCase(this.module.getCode())) {
Good job in adding the spaces

2023-03-21 08:58 UTC, irving11119 requested changes
In general, see my comments as well as others.

2023-03-21 08:58 UTC, irving11119 commented on src/main/java/seedu/apollo/command/module/AddModuleCommand.java
Perhaps you could reduce the nesting here.

2023-03-21 09:16 UTC, T-Wan-Lin commented on src/main/java/seedu/apollo/task/Event.java
> +
Perhaps you could reduce the level of nesting in these 2 methods to make it more readable.

2023-03-23 06:33 UTC, irving11119 requested changes
See my comments for a possible pseudo algo for checking inter event clashing.

2023-03-23 06:33 UTC, irving11119 commented on src/test/java/seedu/apollo/UiTest.java
Possible pseudo algo:

1. Create new event.
2. Get start date/time and end date/time of event.
3. Between these two dates, iterate through every date and obtain a list of all events on that day.
4. Check all events in the list for each day if clashing using start and end time. If clashing return true and print ui message.
5. If no clashing, return false. No need to print.

2023-03-24 14:00 UTC, honglinshang reviewed
lol i forgot to post my review

2023-03-27 09:51 UTC, closed without merging